export const GET_BOOKS = "GET_BOOKS";
export const GET_BOOK_DETAIL = "GET_BOOK_DETAIL";
export const DELETE_BOOK = "DELETE_BOOK";

export const GET_BOOK_INSTANCES = "GET_BOOK_INSTANCES";
export const GET_SINGLE_BOOK_INSTANCE = "GET_SINGLE_BOOK_INSTANCE";
export const DELETE_SINGLE_BOOK_INSTANCE = "DELETE_SINGLE_BOOK_INSTANCE";
export const UPDATE_SINGLE_BOOK_INSTANCE = "UPDATE_SINGLE_BOOK_INSTANCE";
export const CREATE_SINGLE_BOOK_INSTANCE = "CREATE_SINGLE_BOOK_INSTANCE";

export const GET_AUTHORS = "GET_AUTHORS";
export const GET_AUTHOR_DETAIL = "GET_AUTHOR_DETAIL";
export const DELETE_AUTHOR = "DELETE_AUTHOR";

export const POST_GENRES = "POST_GENRES";
export const GET_GENRE_DETAIL = "GET_GENRE_DETAIL";
export const GET_GENRES = "GET_GENRES";

export const SET_TOKEN = "SET_TOKEN";
export const LOG_OUT = "LOG_OUT";

export const GET_DASHBOARD_START = "GET_DASHBOARD_START";
export const GET_DASHBOARD_SUCCESS = "GET_DASHBOARD_SUCCESS";
export const GET_DASHBOARD_FAIL = "GET_DASHBOARD_FAIL";

export const LOADING_START = "LOADING_START";
export const LOADING_FAIL = "LOADING_FAIL";
